---
name: Python Lint

on:
    push:
        branches:
            - main
            - v*.*

    pull_request:
        branches:
            - main
            - v*.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/ruff-action@v3
            - run: ruff format --check --diff
